name: Update Configs
permissions: write-all

on:
  workflow_dispatch:
  push:
    branches:
      - main
  schedule:
    - cron: "*/18 * * * *"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: cd Files && pip install -r requirements.txt

    - name: Run Python script and save output to file
      run: cd Files && python app.py
      
    - name: Run Splitter script and save output to file
      run: cd Files && python sort.py

    - name: Clone private repo
      run: |
        git clone https://x-access-token:${{ secrets.GH_PAT }}@github.com/SublimateTheBerry/proxy-list-private.git private-repo

    - name: Copy generated files
      run: |
        cp -r $(ls | grep -v 'Files\|.git\|.github') private-repo/

    - name: Commit & Push
      run: |
        cd private-repo
        git config user.name "SublimateTheBerry"
        git config user.email "nepan.8066@gmail.com"
        git add .
        git commit -m "Update configs" || echo "No changes to commit"
        git push origin main
